### ISSUE TITLE
Automated Markdown for Metadata

### ISSUE THREAD

**Issue by D-Cobbledick** [datasciencecampus/sdg-indicators#2318] opened 2018-02-14 08:44 UTC
We have a range of excel formulas that automate metadata in markdown from the content of our indicator templates. The aim is to incorporate these to the indicator templates so that we are able to add raw metadata to the tool as markdown with one copy and paste. In trials this has been successful in some instances and has failed in others. Example outputs attached.  Any guidance as to how we need to amend this output would be appreciated. Thanks

[4.2.2.txt](https://github.com/datasciencecampus/sdg-indicators/files/1723208/4.2.2.txt)
[7.3.1.txt](https://github.com/datasciencecampus/sdg-indicators/files/1723209/7.3.1.txt)
[3.3.1.txt](https://github.com/datasciencecampus/sdg-indicators/files/1723210/3.3.1.txt)

**Comment by AnnCorp** [comment] 2018-02-14 10:15
@dougmet is this something you could at least initially explore in Sprint 11 please, in terms of what needs doing and how long it would take please. Dave Cobbledick would be the contact for this.

**Comment by D-Cobbledick** [comment] 2018-02-14 11:38
For info - Most recent tests:

https://github.com/datasciencecampus/sdg-indicators/pull/2323

https://github.com/datasciencecampus/sdg-indicators/pull/2322

https://github.com/datasciencecampus/sdg-indicators/pull/2320

https://github.com/datasciencecampus/sdg-indicators/pull/2319

[4.1.1.txt](https://github.com/datasciencecampus/sdg-indicators/files/1723767/4.1.1.txt)
[16.3.2.txt](https://github.com/datasciencecampus/sdg-indicators/files/1723768/16.3.2.txt)
[1.5.1.txt](https://github.com/datasciencecampus/sdg-indicators/files/1723770/1.5.1.txt)

**Comment by dougmet** [comment] 2018-02-15 15:02
Hi, I fully support this in principle. And it's good seeing the automated checks kicking in as designed. Do you know how to read the error reports? 

From the pull request screen, where the little Travis icon is. Click `details` and it takes you to the build. You're looking for which stage failed. Most of these failed at the metadata check. So for #2323 this had:

```

**Comment by dougmet** [comment] 2018-02-15 15:22
The structure of a page is a mix of Markdown and yaml. E.g.

```
---
# YAML HEADER GOES HERE
title: A nice title
some_key: some value
---

Free form Markdown goes here with **bold!** and things like that.
```

**Comment by D-Cobbledick** [comment] 2018-02-16 10:40
Hi Doug. I'm not sure if I'm reading the error report correctly but I believe the issues on #2322 (lines 39 and 40) are around

un_designated_tier: 'Tier III (a)/Tier II (b,c)'
un_custodian_agency: >-
  United Nations Educational Scientific and Cultural Organization - Institute for Statistics (UNESCO-UIS)

I've modified these slightly from previous pull request but still getting fail (#2329)

**Comment by D-Cobbledick** [comment] 2018-02-20 11:04
[MAXFORD Metadata3.zip](https://github.com/datasciencecampus/sdg-indicators/files/1739811/MAXFORD.Metadata3.zip)

Hi,

I’ve attached a version of the MAXFORD/Indicator template with markdown capability.

All markdown formulas are contained within cells C104:C241 of the metadata tab. These formulas reference cells in the metadata tab and cover tab. Rows 243 to 267 of the metadata tab provide arrays and lookup for automating catch all text. These too reference metadata and cover tabs.

I’ve pasted example cover and metadata information from indicator 4.1.1 as illustration.

The aim is to have a macro button that will copy cells C104:C241 so that metadata data can be pasted into Github as raw markdown.

**Comment by dougmet** [comment] 2018-02-22 10:49
Thanks @D-Cobbledick I've downloaded this and I'm taking a look.

**Comment by dougmet** [comment] 2018-02-22 13:37
For #2329 it's still because `reporting_status` is missing.

**Comment by D-Cobbledick** [comment] 2018-02-26 10:51
Corrected reporting status but still getting error -  Pull Request #2345

**Comment by dougmet** [comment] 2018-02-28 12:13
It needs to be `complete` all lowercase (you have a capital)

**Comment by D-Cobbledick** [comment] 2018-02-28 12:45
That's frustrating! Sorry for the to and fro Doug. I've corrected the capital C but still failing checks 

4.1.1 - metadata - Test 5 #2346

**Comment by AnnCorp** [comment] 2018-02-28 13:46
Hi @D-Cobbledick 
Just to give you the heads up that in my catchup with @dougmet today, we agreed his top priority is getting prep done for the sesh on 19 March (Ghana, Rwanda etc) so this issue may slip down the priority list a bit over the next week or two. Cheers, Ann

**Comment by dougmet** [comment] 2018-02-28 14:48
The new error is a little more cryptic. It's something to do with links but I can't see the cause at the moment.

**Comment by AnnCorp** [comment] 2018-03-01 08:35
@D-Cobbledick if Doug doesn't have resource to look at this during next Sprint, maybe could set up a quick session on 19 March late morning when Doug is at ONS. Bring along Max and Chuck too so can handover work to them.

**Comment by D-Cobbledick** [comment] 2018-03-05 14:19
Okay, that's fine, will do. Cheers, Dave

**Comment by D-Cobbledick** [comment] 2018-03-13 15:58
@dougmet Hi Doug. We're having more success with the markdown tool now. Is there a way to force line breaks in the metadata that displays on the tool? we are able to enter line breaks, bullets etc. in prose and I can add line breaks to raw markdown using double space indent. Either way all text is displaying as single paragraph block.  We've tried running with symbols | and >- to force line break but no joy. Cheers

**Comment by dougmet** [comment] 2018-03-13 20:48
Hi there, that's interesting, I can try a few things. You can also try the escape character `\n` which should be interested as a line break. Failing that you could try an html line break `<br>` or two.

**Comment by D-Cobbledick** [comment] 2018-03-14 08:26
Hi Doug. Thanks for these. I'm afraid we haven't had success with them though. Also, interestingly, in trials where we have passed markdown with line breaks through checks the chart for that indicator has disappeared?? We are going with a single paragraph format for now but maybe something we can chat about on the 19th. Cheers

**Comment by dougmet** [comment] 2018-03-15 09:24
OK sure. Which fields is it btw? There are slight differences in the input boxes.

Also, according to SO the yaml spec does give a way for fine-grained control of line breaks. https://stackoverflow.com/questions/3790454/in-yaml-how-do-i-break-a-string-over-multiple-lines#answer-21699210

**Comment by D-Cobbledick** [comment] 2018-03-15 13:14
Thanks for this Doug. It was fields Definitions and Other Information. We have gone with a single paragraph fix for the time being and now in a sprint to get all new metadata onto the tool. i will try to incorporate line breaks when we get chance though. Cheers

**Comment by AnnCorp** [comment] 2018-03-22 15:13
Think we can close this now and if any specific enhancements then open another ticket.

**Closed** 2018-03-22 15:13 UTC
Labels: Sprint 12
