### ISSUE TITLE
Table columns width

### ISSUE THREAD

**Issue by AnnCorp** [datasciencecampus/sdg-indicators#1944] opened 2017-11-29 11:05 UTC
Need some way  to avoid the data table columns being very wide when the column headings are long.  In current iteration the column heading length dictates column width and the headings can get very long, particularly when going down several layers of the filtering.. 
Need to come up with some options for how could deal with this.
Just for reference:ONS style guide notes " It’s easier to read columns of numbers if they are tightly spaced. Columns should use equal spacing, unless there is a specific reason for altering it. Split column headings over lines to save using wide columns, but choose a sensible place to put the line break."

**Comment by shaneporter** [comment] 2017-11-29 11:51
Removing

```
white-space: nowrap;
```

will be a good starting point.

**Comment by shaneporter** [comment] 2017-12-06 20:43
Please can you provide some examples of indicators with particularly long column headings @AnnCorp? I'd like to see where the problem is most acute.

**Comment by AnnCorp** [comment] 2017-12-08 10:32
@shaneporter How about https://datasciencecampus.github.io/sdg-indicators/3-2-2/ select England and Wales for Geography and then some of the 'Types or registration' are rather long and also NS-SEC. 
Have been thinking should try and aim for max category length for these headings  - may be able to shorten some but sometimes difficult to shorten and maintain enough meaning.

**Comment by AnnCorp** [comment] 2018-01-31 14:42
Included in Sprint 11.  Aiming to review some of the  lengthier descriptions but will still have an issue.
Would be good to  explore what could be done from the quick and easy to the more involved solutions please and dcide from there what route we take.

**Comment by dougmet** [comment] 2018-02-28 11:10
We're investigating some cases where this hasn't worked.

**Comment by shaneporter** [comment] 2018-02-28 18:45
Hmm... I'm still looking into this. I had noticed that an important bit of CSS had been reintroduced, but for my benefit, and possibly the benefit of others, this is how it's looking on my machine right now:

![image](https://user-images.githubusercontent.com/2493614/36806271-6cb8059a-1cb7-11e8-8795-1cd9264a6e48.png)

I'm going to be doing some more checks to see if things are stable in this area before pushing changes.

**Comment by shaneporter** [comment] 2018-03-01 11:54
I believe the 'CSS being introduced' was my doing.

However, the issue is that if you're looking at the table whilst changing selections, all is good. If however, you are making selections and _then_ switch to the table, it's not right.

Still looking at a fix.

**Comment by shaneporter** [comment] 2018-03-06 11:44
Moved into Sprint 12 because of issue, which is hopefully now fixed with PR #2349.

**Closed** 2018-03-06 14:11 UTC
Labels: Sprint 12, enhancement
